### ISSUE TITLE
Receiving an error Cannot find module 'angular2/src/core/compiler/compiler'

### ISSUE THREAD

**Issue by danicomas** [aspnet/NodeServices#17]
```
Hosting environment: Production
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
[Node] module.js:338
[Node]     throw err;
[Node]     ^
[Node]
[Node] Error: Cannot find module 'angular2/src/core/compiler/compiler'
[Node]     at Function.Module._resolveFilename (module.js:336:15)
[Node]     at Function.Module._load (module.js:286:25)
[Node]     at Module.require (module.js:365:17)
[Node]     at require (module.js:384:17)
[Node]     at Object.<anonymous> (C:\Users\daniel.comas\Desktop\Angular2Aspnet5\
Angular2Aspnet5\src\Angular2Aspnet5\node_modules\angular2-universal-patched\dist
\server\src\core\application.js:1:80)
[Node]     at Module._compile (module.js:434:26)
[Node]     at Object.Module._extensions..js (module.js:452:10)
[Node]     at Module.load (module.js:355:32)
[Node]     at Function.Module._load (module.js:310:12)
[Node]     at Module.require (module.js:365:17)
```

I paste my repository url if you know why:

https://github.com/danicomas/Angular2Aspnet5

**Comment by danicomas** [comment]
With this dependencies:

```
{
    "version": "1.0.0",
    "name": "ASP.NET",
    "private": true,
    "dependencies": {
        "es6-module-loader": "0.17.8",
        "systemjs": "0.19.6",
        "reflect-metadata": "0.1.2",
        "traceur": "0.0.92",
        "angular2": "2.0.0-alpha.44",
        "angular2-universal-patched": "0.5.4"
    }
}
```

I receive:

```
Application started. Press Ctrl+C to shut down.
[Node] module.js:338
[Node]     throw err;
[Node]     ^
[Node]
[Node] Error: Cannot find module 'css/lib/parse/index'
[Node]     at Function.Module._resolveFilename (module.js:336:15)
[Node]     at Function.Module._load (module.js:286:25)
[Node]     at Module.require (module.js:365:17)
[Node]     at require (module.js:384:17)
[Node]     at Object.<anonymous> (C:\Users\daniel.comas\Desktop\Angular2Aspnet5\
Angular2Aspnet5\src\Angular2Aspnet5\node_modules\angular2\src\core\dom\parse5_ad
apter.js:10:16)
[Node]     at Module._compile (module.js:434:26)
[Node]     at Object.Module._extensions..js (module.js:452:10)
[Node]     at Module.load (module.js:355:32)
[Node]     at Function.Module._load (module.js:310:12)
[Node]     at Module.require (module.js:365:17)
```

**Comment by SteveSandersonMS** [comment]
The error about `Cannot find module 'angular2/src/core/compiler/compiler'` was because you were using Angular 2 Beta 46. The [`angular-universal`](https://github.com/angular/universal) project has not yet been updated to support that - it only works with beta 44. You could file a bug on that repo or wait for it to be updated.

I'm not sure about the `'css/lib/parse/index'` error but the dependencies as specified on the `MusicStore` example in this repo are working fine for me (including when installing from scratch). Can you try using the same dependencies?

**Comment by SteveSandersonMS** [comment]
BTW make sure you have the latest version of NPM. I've seen people (especially on Windows) run into issues with NPM not fetching all the dependencies because their copy of NPM itself was too old to recognise all parts of the `package.json` format.
